<a href="https://colab.research.google.com/github/newjoseph/DL/blob/main/HiddenLayerIris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Hidden Layer practice usin Iris (classification example)

#import library
import pandas as pd
import tensorflow as tf

#import data from a csv file.
path = "https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv"
iris = pd.read_csv(path)
iris.head()

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종'], dtype='object')


In [6]:
# one-hot encoding

encoding = pd.get_dummies(iris)
encoding.head()


Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [7]:
print(encoding.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [10]:
#separate the variables

ind = encoding[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
de = encoding[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(ind.shape, de.shape)

(150, 4) (150, 3)


In [13]:
# make a model structure

X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8 ,activation='swish')(X) # just make 8 perceptrons (as I choose)
H = tf.keras.layers.Dense(8, activation='swish')(H)
H = tf.keras.layers.Dense(8, activation='swish')(H)
H = tf.keras.layers.Dense(8, activation='swish')(H)
Y = tf.keras.layers.Dense(3, activation ='softmax')(H)
model = tf.keras.models.Model(X,Y)
model.compile(loss = 'categorical_crossentropy', metrics='accuracy')

In [14]:
# fit the model

model.fit(ind, de, epochs= 200, verbose=0)
model.fit(ind, de, epochs = 10)

Epoch 1/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0752 - accuracy: 0.9600
Epoch 2/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0692 - accuracy: 0.9600
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0613 - accuracy: 0.9867
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0685 - accuracy: 0.9800
Epoch 5/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0676 - accuracy: 0.9600
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0680 - accuracy: 0.9733
Epoch 7/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0653 - accuracy: 0.9600
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0609 - accuracy: 0.9667
Epoch 9/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0637 - accuracy: 0.9800
Epoch 10/10
5/5 [==============================] - 0s 4ms/step - loss: 0.0675 - accuracy: 0.9667


In [15]:
# utilize the model

print(model.predict(ind[0:5]))
print(de[0:5])

[[9.9919611e-01 2.2694190e-05 7.8117830e-04]
 [9.9913031e-01 2.7226482e-05 8.4244437e-04]
 [9.9918348e-01 2.3657076e-05 7.9278543e-04]
 [9.9916458e-01 2.4885167e-05 8.1049924e-04]
 [9.9920988e-01 2.1813499e-05 7.6825672e-04]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
